// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFvXkLy4YYTfwUc8Av3RLRA_EdbwkJyoM',
    appId: '1:1098557927547:web:318aa6da64cbd72d2732de',
    messagingSenderId: '1098557927547',
    projectId: 'fenerbahce-33218',
    authDomain: 'fenerbahce-33218.firebaseapp.com',
    storageBucket: 'fenerbahce-33218.appspot.com',
    measurementId: 'G-R8R290F805',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhjLq_Q8UTICqye092-79QTtUtBc2HQSc',
    appId: '1:1098557927547:android:c8a7761c24b2caf62732de',
    messagingSenderId: '1098557927547',
    projectId: 'fenerbahce-33218',
    storageBucket: 'fenerbahce-33218.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBds06Ihj2tpGPLnybyZTFRUhr6I2eu6_U',
    appId: '1:1098557927547:ios:1bdea63d203fc5ac2732de',
    messagingSenderId: '1098557927547',
    projectId: 'fenerbahce-33218',
    storageBucket: 'fenerbahce-33218.appspot.com',
    iosBundleId: 'com.example.fenerbahce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBds06Ihj2tpGPLnybyZTFRUhr6I2eu6_U',
    appId: '1:1098557927547:ios:1bdea63d203fc5ac2732de',
    messagingSenderId: '1098557927547',
    projectId: 'fenerbahce-33218',
    storageBucket: 'fenerbahce-33218.appspot.com',
    iosBundleId: 'com.example.fenerbahce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDFvXkLy4YYTfwUc8Av3RLRA_EdbwkJyoM',
    appId: '1:1098557927547:web:adad1978eca4dbba2732de',
    messagingSenderId: '1098557927547',
    projectId: 'fenerbahce-33218',
    authDomain: 'fenerbahce-33218.firebaseapp.com',
    storageBucket: 'fenerbahce-33218.appspot.com',
    measurementId: 'G-1SP72YTGWC',
  );
}
